export const clientEnv = {
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME:
    process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME,

  NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET:
    process.env.NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET,

  NEXT_PUBLIC_LOCATIONIQ_KEY: process.env.NEXT_PUBLIC_LOCATIONIQ_KEY,
};
